{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.jar",
          "url": "url-builder-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.jar",
          "size": 5981,
          "sha512": "54c18e6c218a70f7762e500646a2dfb3c70d85cfee413a6704fd8753804053b7b46cb9977bfd36b7dde1ab7a8cefea73fe663ba7bd35f69d586f83476ee1e607",
          "sha256": "c3e66b7759957804a0d0c164e7c967e71d13cf064c137e868b40114694871a2d",
          "sha1": "90b21aea315aba2405b73a150515c56322e6f05b",
          "md5": "0357e3f73e688b4bdf9643cd7748ea34"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461/url-builder-js-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461/url-builder-js-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461/url-builder-jvm-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461/url-builder-jvm-2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "2.0.0-b7e21b12ef94d3d5a0f6459cdbc660609f80f461"
      }
    }
  ]
}
