{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "px4qsg2qkbef5oq36xdyflrp4e"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27726,
          "sha512": "a6b4bc34753b3e58ecd6b8d129bb553d0e6694942df0e642e9268d582838a06a50421749c0dc10c74b16b319c8bd3e76062ff50db93ff2be44cc835bd67c8f7d",
          "sha256": "37d8d9e35e66c81a4054cd13fa26946d94ec2a53b5d5b950f864cbbee97b3618",
          "sha1": "84232a754c74bb85b2b328a16e402647452aa555",
          "md5": "2917f10c77ba6045f316cc803a9696a2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27726,
          "sha512": "a6b4bc34753b3e58ecd6b8d129bb553d0e6694942df0e642e9268d582838a06a50421749c0dc10c74b16b319c8bd3e76062ff50db93ff2be44cc835bd67c8f7d",
          "sha256": "37d8d9e35e66c81a4054cd13fa26946d94ec2a53b5d5b950f864cbbee97b3618",
          "sha1": "84232a754c74bb85b2b328a16e402647452aa555",
          "md5": "2917f10c77ba6045f316cc803a9696a2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.7-SNAPSHOT/url-builder-metadata-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.7-SNAPSHOT"
      }
    }
  ]
}
