{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27571,
          "sha512": "8dc081d39ea71ffdff9dd1a77e93fc1391454dd86559b660e3720128e4001a436a0359358dc52569a1c5c71994e5320029c7a86ed234c95f7663038c65ce28f3",
          "sha256": "e9d9e24bec337bd60f53df3782915c048332c18763c266bf89998941d7f96745",
          "sha1": "ae6955f7c9a8d320f0759c714385c4a4de62fc1f",
          "md5": "e9899ec435772ed59314c896a7211a14"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27571,
          "sha512": "8dc081d39ea71ffdff9dd1a77e93fc1391454dd86559b660e3720128e4001a436a0359358dc52569a1c5c71994e5320029c7a86ed234c95f7663038c65ce28f3",
          "sha256": "e9d9e24bec337bd60f53df3782915c048332c18763c266bf89998941d7f96745",
          "sha1": "ae6955f7c9a8d320f0759c714385c4a4de62fc1f",
          "md5": "e9899ec435772ed59314c896a7211a14"
        }
      ]
    }
  ]
}
