{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27564,
          "sha512": "df4d01bded8555702982c93513c90ef3fc78f05c94de75a91c12c0e1a30ded39bbfd0172d058eddf6e7b8d7008750741ee2257194286cc6c5675fddffefd1d8d",
          "sha256": "e9169751996e7a54f89a6a5b72177d264167caaefd266f0d49ada69587d99183",
          "sha1": "502c32fa0ea09cfdf2197fc36435fcb9238f0f8f",
          "md5": "0fbcabb107e195dc6c7c3e93041adfad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.7-SNAPSHOT.jar",
          "size": 27564,
          "sha512": "df4d01bded8555702982c93513c90ef3fc78f05c94de75a91c12c0e1a30ded39bbfd0172d058eddf6e7b8d7008750741ee2257194286cc6c5675fddffefd1d8d",
          "sha256": "e9169751996e7a54f89a6a5b72177d264167caaefd266f0d49ada69587d99183",
          "sha1": "502c32fa0ea09cfdf2197fc36435fcb9238f0f8f",
          "md5": "0fbcabb107e195dc6c7c3e93041adfad"
        }
      ]
    }
  ]
}
