{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinxpath/2.0/kotlinxpath-2.0.module",
    "group": "io.github.detachhead",
    "module": "kotlinxpath",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fpkywmy4rvbfdh6mqcywu52vpm"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-js-2.0.jar",
          "url": "kotlinxpath-js-2.0.jar",
          "size": 91720,
          "sha512": "6fe09721d2a7d8a47a99972c9d212a21a395b6b17a0051d1a13dff107bcb20f49329045ffc1f07187ae62e787691c671d40d61d53b4cdc23cf85dfe1c79b5c6f",
          "sha256": "ed45636626fdf04f360b50521f25ece45b53d6dd5850b555358a47d55be2959a",
          "sha1": "baa37c09a76cd52821e4f1d88c0b22c5c4996ddf",
          "md5": "d752d512fb0f8f5beda4dfb88888a6f8"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-js-2.0.jar",
          "url": "kotlinxpath-js-2.0.jar",
          "size": 91720,
          "sha512": "6fe09721d2a7d8a47a99972c9d212a21a395b6b17a0051d1a13dff107bcb20f49329045ffc1f07187ae62e787691c671d40d61d53b4cdc23cf85dfe1c79b5c6f",
          "sha256": "ed45636626fdf04f360b50521f25ece45b53d6dd5850b555358a47d55be2959a",
          "sha1": "baa37c09a76cd52821e4f1d88c0b22c5c4996ddf",
          "md5": "d752d512fb0f8f5beda4dfb88888a6f8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinxpath-metadata/2.0/kotlinxpath-metadata-2.0.module",
        "group": "io.github.detachhead",
        "module": "kotlinxpath-metadata",
        "version": "2.0"
      }
    }
  ]
}
