{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7/url-builder-1.0.7.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "l2tbwd2rcfafbhdtzgc34jjor4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7.klib",
          "url": "url-builder-js-1.0.7.klib",
          "size": 19536,
          "sha512": "f4596a73e874f53ff359a710f0ab1c98825dcc47c7cdaaee59afd4ab055831e26bf86fbab3bc454b2abdb797203d7fdc927848c16d0c00f7fa9b823e29ef4bbd",
          "sha256": "5a71bb1ed1aab0cff570a90daddfb23a2a83d723aaad86f31ac4585c85864426",
          "sha1": "12210a819d0534fe95ed5108388d0f79ee2dabdf",
          "md5": "d2348f8f2702cba6fa36034fc98c61fa"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7.klib",
          "url": "url-builder-js-1.0.7.klib",
          "size": 19536,
          "sha512": "f4596a73e874f53ff359a710f0ab1c98825dcc47c7cdaaee59afd4ab055831e26bf86fbab3bc454b2abdb797203d7fdc927848c16d0c00f7fa9b823e29ef4bbd",
          "sha256": "5a71bb1ed1aab0cff570a90daddfb23a2a83d723aaad86f31ac4585c85864426",
          "sha1": "12210a819d0534fe95ed5108388d0f79ee2dabdf",
          "md5": "d2348f8f2702cba6fa36034fc98c61fa"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.7/url-builder-metadata-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.7"
      }
    }
  ]
}
