{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "cspvxcrxcbfjhhph2svqe6cszy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "1bc5b2eeac5b2b5b74b9c412cf6e112e1ad7b7ca2c81fcf73f3dbcd3e5da1d68e28b288e00b012ffa58d69c950da0936e0f472318d9004c5b1bb06764d7af222",
          "sha256": "4021fbcc34bc22dc3b2e9dead027d4447bf559a3b0f24dc81975cdf07af9cf36",
          "sha1": "b0c2fc97dc67ab8e599630734ae6f004fd002205",
          "md5": "0d4e5f811f6ee0a68db74308a914df23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "1bc5b2eeac5b2b5b74b9c412cf6e112e1ad7b7ca2c81fcf73f3dbcd3e5da1d68e28b288e00b012ffa58d69c950da0936e0f472318d9004c5b1bb06764d7af222",
          "sha256": "4021fbcc34bc22dc3b2e9dead027d4447bf559a3b0f24dc81975cdf07af9cf36",
          "sha1": "b0c2fc97dc67ab8e599630734ae6f004fd002205",
          "md5": "0d4e5f811f6ee0a68db74308a914df23"
        }
      ]
    }
  ]
}
