{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder-jvm/1.0.7-SNAPSHOT/url-builder-jvm-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder-jvm",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "76al7ezkmngljife2oekmeurpq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-metadata-1.0.7-SNAPSHOT.jar",
          "size": 4494,
          "sha512": "3eb0825397dc53847687e7b77b6c62dcd40f91b6d9fd3ab611a3be59aa6de044a41d5f50f5b5994cefeba8e99fa1725ac8309f77572a2a83e1f92fd31dc68030",
          "sha256": "dd8f222087ff88ec7a442e78d64e28e0cf3ea10621fda9a8bff3a9064a460c94",
          "sha1": "f2194d56498a0175306e9a5237e7c163caead1fa",
          "md5": "d2b60db51ce1fc3532e50ae83894d2a5"
        }
      ]
    }
  ]
}
