{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinxpath/2.0-SNAPSHOT/kotlinxpath-2.0-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "kotlinxpath",
    "version": "2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "2isljhqe2zh2jf54q4szsxfqny"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-jvm-2.0-SNAPSHOT.jar",
          "url": "kotlinxpath-jvm-2.0-SNAPSHOT.jar",
          "size": 62520,
          "sha512": "d5ad2ea9a01fc00a7de38f9df7c4b91de58d7fa6520504e88d1b6d843e6045ba3633bcdd90aac8fd3a23a4127cbdab0d92f04111102a00485d0b8632320390ab",
          "sha256": "272712840f71adc61af90d84cfbdfb50f53ecca5f8af1925b3cb6102869aefc0",
          "sha1": "278888802ca9c37287b276bc3333617cbcda3daf",
          "md5": "70248721b7eee9f41618096f8d650b02"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-jvm-2.0-SNAPSHOT.jar",
          "url": "kotlinxpath-jvm-2.0-SNAPSHOT.jar",
          "size": 62520,
          "sha512": "d5ad2ea9a01fc00a7de38f9df7c4b91de58d7fa6520504e88d1b6d843e6045ba3633bcdd90aac8fd3a23a4127cbdab0d92f04111102a00485d0b8632320390ab",
          "sha256": "272712840f71adc61af90d84cfbdfb50f53ecca5f8af1925b3cb6102869aefc0",
          "sha1": "278888802ca9c37287b276bc3333617cbcda3daf",
          "md5": "70248721b7eee9f41618096f8d650b02"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinxpath-metadata/2.0-SNAPSHOT/kotlinxpath-metadata-2.0-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "kotlinxpath-metadata",
        "version": "2.0-SNAPSHOT"
      }
    }
  ]
}
