{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder-url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vqkwyk7omraz3l5apegrx3holu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "size": 261,
          "sha512": "6cb6e15ba50f6441125b8d65feadb3f78245c16a81c10dfbdbb5cbb2d21670641190800ccbec7aad491b22315c0ad2bc35a521be3aebc9202a901ab5f5a3d1a1",
          "sha256": "2e01faadee9cc471e6f7eee4367d7a15e5739822d0e1d030e907289fef7f80b9",
          "sha1": "b7a3408c934de62a30513f63130ee980446222e9",
          "md5": "0db48660eafaab7fd07057e6d4c27258"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "size": 261,
          "sha512": "6cb6e15ba50f6441125b8d65feadb3f78245c16a81c10dfbdbb5cbb2d21670641190800ccbec7aad491b22315c0ad2bc35a521be3aebc9202a901ab5f5a3d1a1",
          "sha256": "2e01faadee9cc471e6f7eee4367d7a15e5739822d0e1d030e907289fef7f80b9",
          "sha1": "b7a3408c934de62a30513f63130ee980446222e9",
          "md5": "0db48660eafaab7fd07057e6d4c27258"
        }
      ]
    }
  ]
}
