{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7/url-builder-1.0.7.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "l2tbwd2rcfafbhdtzgc34jjor4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7.jar",
          "url": "url-builder-jvm-1.0.7.jar",
          "size": 27719,
          "sha512": "5afc8e8e88a9f2b17005a5c3d0fd052404e34c9c18fda39a9c0b297f4f01413c1f412533d8c106a10c55b23655d8baeefa1151779882199ea19ca8ff9c45efd5",
          "sha256": "08db3d46b8f021bda2ba5a7bffcb9700d64fee49b2ae8533ca944838c48d001e",
          "sha1": "dc93b0a7171862f00e8d15cbde94c4ee6984e920",
          "md5": "b1af3e0ba25341d216be560b5fedafb3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7.jar",
          "url": "url-builder-jvm-1.0.7.jar",
          "size": 27719,
          "sha512": "5afc8e8e88a9f2b17005a5c3d0fd052404e34c9c18fda39a9c0b297f4f01413c1f412533d8c106a10c55b23655d8baeefa1151779882199ea19ca8ff9c45efd5",
          "sha256": "08db3d46b8f021bda2ba5a7bffcb9700d64fee49b2ae8533ca944838c48d001e",
          "sha1": "dc93b0a7171862f00e8d15cbde94c4ee6984e920",
          "md5": "b1af3e0ba25341d216be560b5fedafb3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.7/url-builder-metadata-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.7"
      }
    }
  ]
}
