{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7/url-builder-1.0.7.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7.jar",
          "url": "url-builder-jvm-1.0.7.jar",
          "size": 27569,
          "sha512": "323ce23e02f3cba0dff17dae581937913e0ffa91c8a258225b9113ea205b5c7bfe9c6f792a92ac4e30793edc9b8151ca5474bdad4e948a84da56fcf1d46e67ff",
          "sha256": "90a66f21155724664ac85257ae258b390c6fa86794a2e2ab4983c6690ffd9581",
          "sha1": "15505f51f20a8c2932ef3072702da80e3fcefa97",
          "md5": "e60a3c76fe89a3101a903e0306819953"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.7.jar",
          "url": "url-builder-jvm-1.0.7.jar",
          "size": 27569,
          "sha512": "323ce23e02f3cba0dff17dae581937913e0ffa91c8a258225b9113ea205b5c7bfe9c6f792a92ac4e30793edc9b8151ca5474bdad4e948a84da56fcf1d46e67ff",
          "sha256": "90a66f21155724664ac85257ae258b390c6fa86794a2e2ab4983c6690ffd9581",
          "sha1": "15505f51f20a8c2932ef3072702da80e3fcefa97",
          "md5": "e60a3c76fe89a3101a903e0306819953"
        }
      ]
    }
  ]
}
