{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder-url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "l2tbwd2rcfafbhdtzgc34jjor4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7.jar",
          "url": "url-builder-url-builder-1.0.7.jar",
          "size": 261,
          "sha512": "ae81a67005015f932222f667fb7953b9372007701601d92098b707fb619a9cafc998bb89875da93683872d03cf207c3c47946ff887faed12b834eea0613f41d4",
          "sha256": "c8691ea52494989efdf21fd87e9acac0a10e27eb1d54e6e8dcf214207ad8fe85",
          "sha1": "0f8f689b741799a737359abaa851e0e53d09172a",
          "md5": "7dbe67550b30ea60cb950f8b73f56d56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7.jar",
          "url": "url-builder-url-builder-1.0.7.jar",
          "size": 261,
          "sha512": "ae81a67005015f932222f667fb7953b9372007701601d92098b707fb619a9cafc998bb89875da93683872d03cf207c3c47946ff887faed12b834eea0613f41d4",
          "sha256": "c8691ea52494989efdf21fd87e9acac0a10e27eb1d54e6e8dcf214207ad8fe85",
          "sha1": "0f8f689b741799a737359abaa851e0e53d09172a",
          "md5": "7dbe67550b30ea60cb950f8b73f56d56"
        }
      ]
    }
  ]
}
