{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder-jvm/1.0.8-SNAPSHOT/url-builder-jvm-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder-jvm",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "icjnkmrakffuhirrrbovadbhie"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "size": 4494,
          "sha512": "e23ed3b74e9687f7e04dada0346a412b89771d833cf732017d595681baec6d538db3a2e2b7b5315cba8aabaf9aa6e572cc41ef03dc2dab1ef636763f4835d777",
          "sha256": "6ea451fc54a7263464ea56139a3f63ee6b27f2bf7f78e4f44d191dfbec8dff6b",
          "sha1": "525acc58a236500651d510a0fc1c5459a91ba196",
          "md5": "00a3d2d225b020f5eb2a8e3b487cee8c"
        }
      ]
    }
  ]
}
