{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder-jvm/1.0.8-SNAPSHOT/url-builder-jvm-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder-jvm",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ffgtgvr5qvc5jiu4v2mcl62hbm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "size": 4494,
          "sha512": "a310a4121e1a2926a3da2145038e632908691472cb1dd649d5064c15012d9cdd63762389c8437f5c036a56a148fa690a8822e8fca5d654e18eb3dea665bc8ed8",
          "sha256": "d2338f9f165e155b90d98d5ccc7df7697f6495c3d76aa83afcab086c46c5c1a1",
          "sha1": "b462bacb6358af1491a8c20bf0fb9c84e185388d",
          "md5": "dd36d745ec7eb6a565948eb9e17e8322"
        }
      ]
    }
  ]
}
