{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder-jvm/1.0.8-SNAPSHOT/url-builder-jvm-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder-jvm",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "odoqbcldhbal5enk5wq73pevge"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-metadata-1.0.8-SNAPSHOT.jar",
          "size": 4494,
          "sha512": "9cf0996a493d0337ca8f7ce2d9dad2b28607bdf194585b6c2dbd046d15cef628a9bfed880acf1e2405641b544e0a33aab012aad810436733281345510322d23d",
          "sha256": "b003203a373b7465d10f27db2924d70c969e635d66c4b6546e5cbec68a11997e",
          "sha1": "44bc11bf18e3e2b7c8d22ffb06a17a23959eeb70",
          "md5": "ad679273bb38170d50ef32b73cc36ccc"
        }
      ]
    }
  ]
}
