{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "odoqbcldhbal5enk5wq73pevge"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "d36d5b3e508802fff0ca57da70b01eec4306ab96e95271374dd6a97dcd018c4352f13904f4173c9a50c85b392beb057ce8118a6e05e3431c3f89a3d643d251b5",
          "sha256": "f361e76ee5273c278fd185240c1ca0a0c85b69bd90f73027ef0f1edd587c9b45",
          "sha1": "69dbe84fd54fb20d12132a12e24d44c1e2f1a412",
          "md5": "2471cc0d0f85172a5f7d1cbfee5e3821"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "d36d5b3e508802fff0ca57da70b01eec4306ab96e95271374dd6a97dcd018c4352f13904f4173c9a50c85b392beb057ce8118a6e05e3431c3f89a3d643d251b5",
          "sha256": "f361e76ee5273c278fd185240c1ca0a0c85b69bd90f73027ef0f1edd587c9b45",
          "sha1": "69dbe84fd54fb20d12132a12e24d44c1e2f1a412",
          "md5": "2471cc0d0f85172a5f7d1cbfee5e3821"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
