{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ffgtgvr5qvc5jiu4v2mcl62hbm"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "15e82f722c2471874c8458b6568599ce32953fd5846279aaa13d5e802a575666792f7c258a6c561b36de8e61ab0661c5c38a3b3cb749f8471932e1120817b4e7",
          "sha256": "2ed6a96c5df6c9f0b9edec1ed2df439a2f34b95f1fad29cc3e826d7471ac538b",
          "sha1": "43278df7dc63850084a93d1ae62e7f050c07443c",
          "md5": "bb014fa3dfc3956a3199aa640ee751e0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.8-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "15e82f722c2471874c8458b6568599ce32953fd5846279aaa13d5e802a575666792f7c258a6c561b36de8e61ab0661c5c38a3b3cb749f8471932e1120817b4e7",
          "sha256": "2ed6a96c5df6c9f0b9edec1ed2df439a2f34b95f1fad29cc3e826d7471ac538b",
          "sha1": "43278df7dc63850084a93d1ae62e7f050c07443c",
          "md5": "bb014fa3dfc3956a3199aa640ee751e0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
