{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "l2tbwd2rcfafbhdtzgc34jjor4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.7.jar",
          "url": "url-builder-1.0.7.jar",
          "size": 4494,
          "sha512": "c86d5aea7ae29f9661256d24eb738b963b6a29368a2b987e25a809a32f6ece7c0248e4dfe12a83d0b6981043c923a03f3630fd81ab3f3046106b2b561d7a65ac",
          "sha256": "cbb3836b9f6946b77bbd9b344e6d95ffa0536af56ddc11a5c8681f372ec48939",
          "sha1": "cb3d9c56fc077ea54a6fd2be3f33699216562395",
          "md5": "f50c778c1f4ad4269834db96922bd298"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7/url-builder-js-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7/url-builder-js-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7/url-builder-jvm-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7/url-builder-jvm-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7"
      }
    }
  ]
}
