{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "53dzceyc5zaovfbxjwlkdn5oxy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.7.jar",
          "url": "url-builder-1.0.7.jar",
          "size": 4494,
          "sha512": "b7605a119cbffbb7d7f519e1f41cf7f1c9c90fdc064993c7b6c9fcec05d715503fe797dd12dd6daed9dfebd24b6964ddbcb7cdb241542e3f3b7885713be045ca",
          "sha256": "bca0762e3d29eb48c28836e6334e67ff69d52a6542447dcd0cb84b61eda0aec7",
          "sha1": "e57f6c902ede7a2832b7918ecfb633ef76cfd931",
          "md5": "1a752d2b9218721fe8c614d9aaf57b8b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7/url-builder-js-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7/url-builder-js-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7/url-builder-jvm-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7/url-builder-jvm-1.0.7.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7"
      }
    }
  ]
}
