{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "size": 17737,
          "sha512": "8d57cc5bbcbb2d06a43f8647342e8a4cb247a3df10c1cb2035fbc9af42fee5cbb75edec8416116cee7e3413aa31e7b52f417642d88d1721df84b8e2f219aa1ea",
          "sha256": "0ceec36268502f09eede20739b4b071b622978ff692878e76049d1c7bcff51ce",
          "sha1": "6a0301bd2c31e8fa9e15e6ed497ab356b2138d29",
          "md5": "a4132442b3f975b061c338c5a8bc2e17"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "size": 17737,
          "sha512": "8d57cc5bbcbb2d06a43f8647342e8a4cb247a3df10c1cb2035fbc9af42fee5cbb75edec8416116cee7e3413aa31e7b52f417642d88d1721df84b8e2f219aa1ea",
          "sha256": "0ceec36268502f09eede20739b4b071b622978ff692878e76049d1c7bcff51ce",
          "sha1": "6a0301bd2c31e8fa9e15e6ed497ab356b2138d29",
          "md5": "a4132442b3f975b061c338c5a8bc2e17"
        }
      ]
    }
  ]
}
