{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wagc666ocnambebhnwa4oucol4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.7-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "6a3150d70983505263604b9f3181fd12cfef77a0924dc5138a58b2fcf4102f49303d8088eea4ff737d95c2499ca6136bfce797e0a859af03f7e85412a341b1ad",
          "sha256": "d77cae190bae92f16bec0fdd04298dc9056ea76453f4bf82f70c0a9a53d00be6",
          "sha1": "7af3f7accd5241a8e75d4e45ffe2947d7cdcca63",
          "md5": "c3e506380ce3187d19e1a426ed36e7e2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.klib",
          "url": "url-builder-js-1.0.7-SNAPSHOT.klib",
          "size": 19536,
          "sha512": "6a3150d70983505263604b9f3181fd12cfef77a0924dc5138a58b2fcf4102f49303d8088eea4ff737d95c2499ca6136bfce797e0a859af03f7e85412a341b1ad",
          "sha256": "d77cae190bae92f16bec0fdd04298dc9056ea76453f4bf82f70c0a9a53d00be6",
          "sha1": "7af3f7accd5241a8e75d4e45ffe2947d7cdcca63",
          "md5": "c3e506380ce3187d19e1a426ed36e7e2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.7-SNAPSHOT/url-builder-metadata-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.7-SNAPSHOT"
      }
    }
  ]
}
