{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.7-SNAPSHOT/url-builder-1.0.7-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "size": 17737,
          "sha512": "74920c758130b21dde0eac2dea47801b89ceee101ef793ad8f215091d7c3a4f4394b4a56d37ef16a1972bbd5c2c29b1d1707eb1f89df8f43fe4d424fb4f443fd",
          "sha256": "2f84503ab4c2f58f110257118002ca44728ee5854d3f1fa943d0c028aab5bde3",
          "sha1": "8eedd1b0b7e2b551e96c4db0f8d87d57cac36503",
          "md5": "f16177519f3de2557b46af5f8bc29c73"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-js-1.0.7-SNAPSHOT.jar",
          "size": 17737,
          "sha512": "74920c758130b21dde0eac2dea47801b89ceee101ef793ad8f215091d7c3a4f4394b4a56d37ef16a1972bbd5c2c29b1d1707eb1f89df8f43fe4d424fb4f443fd",
          "sha256": "2f84503ab4c2f58f110257118002ca44728ee5854d3f1fa943d0c028aab5bde3",
          "sha1": "8eedd1b0b7e2b551e96c4db0f8d87d57cac36503",
          "md5": "f16177519f3de2557b46af5f8bc29c73"
        }
      ]
    }
  ]
}
