{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder-url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "k4wsxzgz4rblnacqthpenz6txu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "1bfcbaae1d382869dbecf5fdf86c97c7369f9f433a69ab2874f523ef1aee01050dc7e1f7e50a437e9008613a2398bcf494f703c5191fa6b3dcad15b1737eea94",
          "sha256": "7040de20098e9fffdaaf7a6cfb235a16bb8e8e7cc886255cd2d1515f52404afe",
          "sha1": "2f2c228d99ae1b04ad5e3d7f246e55c2c12858b6",
          "md5": "a9329a4c0298204a2d0b996c2f214169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "1bfcbaae1d382869dbecf5fdf86c97c7369f9f433a69ab2874f523ef1aee01050dc7e1f7e50a437e9008613a2398bcf494f703c5191fa6b3dcad15b1737eea94",
          "sha256": "7040de20098e9fffdaaf7a6cfb235a16bb8e8e7cc886255cd2d1515f52404afe",
          "sha1": "2f2c228d99ae1b04ad5e3d7f246e55c2c12858b6",
          "md5": "a9329a4c0298204a2d0b996c2f214169"
        }
      ]
    }
  ]
}
