{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder-url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ffgtgvr5qvc5jiu4v2mcl62hbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "435a7ac7121d18d77e79b154115c7328d9908b260f83bea8b99c9c3fcb0dca4ab36c1b9386d008f470f93788ab7eb330219371db9572ca9f06cab673875b1774",
          "sha256": "983fe946b34080ab6e779cd074378649851e74263d44a4d2818797a70b56f865",
          "sha1": "dc33e138b4477709352c87a890685cf3126d81f7",
          "md5": "4bdf90911bb48a59c69c4bfbf18677cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "435a7ac7121d18d77e79b154115c7328d9908b260f83bea8b99c9c3fcb0dca4ab36c1b9386d008f470f93788ab7eb330219371db9572ca9f06cab673875b1774",
          "sha256": "983fe946b34080ab6e779cd074378649851e74263d44a4d2818797a70b56f865",
          "sha1": "dc33e138b4477709352c87a890685cf3126d81f7",
          "md5": "4bdf90911bb48a59c69c4bfbf18677cd"
        }
      ]
    }
  ]
}
