{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinxpath/2.0/kotlinxpath-2.0.module",
    "group": "io.github.detachhead",
    "module": "kotlinxpath",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fpkywmy4rvbfdh6mqcywu52vpm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-metadata-2.0.jar",
          "url": "kotlinxpath-metadata-2.0.jar",
          "size": 14629,
          "sha512": "ff64783cfad35d00e8c83004a60baaf15c4b27bceaa82d2e0dc247cef5146580e4ff3652db79d2a29614090277afdb457cbb75ca5c5fb7e872d9483ba90be003",
          "sha256": "2e23fa840fbfd6f1dfba15dbe2b2d19476ebf2254f7e471756e9f03f69b2b56f",
          "sha1": "3e8f4d1594ef9bf271fced7b7275e0b17a6c4c32",
          "md5": "719234251b1e28ba10621b30dda0730c"
        }
      ]
    }
  ]
}
