{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "icjnkmrakffuhirrrbovadbhie"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27727,
          "sha512": "b56feb35b534fc2805991a8ff169b225a0427b3ea142a5b5751c078d21c414ac82fc0a047775c6840f9f7d9b958130924956327db7035684feef74ce6f9fe164",
          "sha256": "80f4f9632f6adc9d851a23381ff580b23030a91cdfdae345e585455b394e29c8",
          "sha1": "39bcfee38a7610cc28b329aaca3e793ae210e188",
          "md5": "d3443d1fa2f1f2f9f1a5e190a5f059e7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27727,
          "sha512": "b56feb35b534fc2805991a8ff169b225a0427b3ea142a5b5751c078d21c414ac82fc0a047775c6840f9f7d9b958130924956327db7035684feef74ce6f9fe164",
          "sha256": "80f4f9632f6adc9d851a23381ff580b23030a91cdfdae345e585455b394e29c8",
          "sha1": "39bcfee38a7610cc28b329aaca3e793ae210e188",
          "md5": "d3443d1fa2f1f2f9f1a5e190a5f059e7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
