{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "agyx655ve5flhfgsvtx3ljp2e4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27726,
          "sha512": "4953f0f69aa63e0c343d777e11c03b39cd1fa13917d1eceea46c92fb35bc840148868517f614ff9343e29e55ccf4f3051ee1a1f2b406a6ee03869e4dbd6fba2e",
          "sha256": "a92dfbe6525a7b0a7b9442dccf207127767e3870351f8736ed2b06fd2f61254d",
          "sha1": "7d3979e5562dc24c5fcbcf5290de2269323b9da9",
          "md5": "2ef0f9c86646475be7b3988eac8a1845"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27726,
          "sha512": "4953f0f69aa63e0c343d777e11c03b39cd1fa13917d1eceea46c92fb35bc840148868517f614ff9343e29e55ccf4f3051ee1a1f2b406a6ee03869e4dbd6fba2e",
          "sha256": "a92dfbe6525a7b0a7b9442dccf207127767e3870351f8736ed2b06fd2f61254d",
          "sha1": "7d3979e5562dc24c5fcbcf5290de2269323b9da9",
          "md5": "2ef0f9c86646475be7b3988eac8a1845"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
