{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "odoqbcldhbal5enk5wq73pevge"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27705,
          "sha512": "ce4d1652f409c830996bdd76e9c49149a186bf04393b6d64e5039b4152f57a41ace17bb993fae0a409914e00efa11f5c9631e9e69212648ba63efda0c497340d",
          "sha256": "1d1f7908f689e84c88e624732df042b138a5776e14bcdec2a80b09df2d1ac683",
          "sha1": "df615200da276404d0a374e1cdfaffcf177e5170",
          "md5": "61f45a6b2563fe8a707cdfdcf412d2e9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27705,
          "sha512": "ce4d1652f409c830996bdd76e9c49149a186bf04393b6d64e5039b4152f57a41ace17bb993fae0a409914e00efa11f5c9631e9e69212648ba63efda0c497340d",
          "sha256": "1d1f7908f689e84c88e624732df042b138a5776e14bcdec2a80b09df2d1ac683",
          "sha1": "df615200da276404d0a374e1cdfaffcf177e5170",
          "md5": "61f45a6b2563fe8a707cdfdcf412d2e9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
