{
  "formatVersion": "1.1",
  "component": {
    "url": "../../url-builder/1.0.8-SNAPSHOT/url-builder-1.0.8-SNAPSHOT.module",
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "ga47vgbrcza3vctrrvb54hhadu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27708,
          "sha512": "7a06764907b7345add7ae68465ae808bd3a34ad1d93414817d17c2c412e76c905ca83d028f98ea9da9d5340e2047e341219a58d7d33b68968bed28497a9891d3",
          "sha256": "ab6584437755c6d055805a0c5603ce797f941058ddc56dd5283bc36ddd30c98e",
          "sha1": "545aa26e864b2e2224866eae40bc8f7fc60d1b8d",
          "md5": "10e493e95d66162c29b22a005d06ff70"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "url": "url-builder-jvm-1.0.8-SNAPSHOT.jar",
          "size": 27708,
          "sha512": "7a06764907b7345add7ae68465ae808bd3a34ad1d93414817d17c2c412e76c905ca83d028f98ea9da9d5340e2047e341219a58d7d33b68968bed28497a9891d3",
          "sha256": "ab6584437755c6d055805a0c5603ce797f941058ddc56dd5283bc36ddd30c98e",
          "sha1": "545aa26e864b2e2224866eae40bc8f7fc60d1b8d",
          "md5": "10e493e95d66162c29b22a005d06ff70"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../url-builder-metadata/1.0.8-SNAPSHOT/url-builder-metadata-1.0.8-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-metadata",
        "version": "1.0.8-SNAPSHOT"
      }
    }
  ]
}
