{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder-url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "hbqdanavfjhjvgxmofxza4ii3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "size": 261,
          "sha512": "a1aef4b4061656233cac5e6770a096e88efce52932bade4dff9ddb6c8858cca2606ad5964ce456c7096c1230ad518731ff0ca6e63f76b7bcb3a4b027d9db9a6d",
          "sha256": "c15a6034b0912dc71c7c64e5988d3c9fde7ef53c87ff232588ac3c66cda5586e",
          "sha1": "030bac830bbf7abb6f12397ce165bbb45af4273c",
          "md5": "5265d498ec2014456172aadccd399824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-url-builder-1.0.7-SNAPSHOT.jar",
          "size": 261,
          "sha512": "a1aef4b4061656233cac5e6770a096e88efce52932bade4dff9ddb6c8858cca2606ad5964ce456c7096c1230ad518731ff0ca6e63f76b7bcb3a4b027d9db9a6d",
          "sha256": "c15a6034b0912dc71c7c64e5988d3c9fde7ef53c87ff232588ac3c66cda5586e",
          "sha1": "030bac830bbf7abb6f12397ce165bbb45af4273c",
          "md5": "5265d498ec2014456172aadccd399824"
        }
      ]
    }
  ]
}
