{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinxpath/2.0/kotlinxpath-2.0.module",
    "group": "io.github.detachhead",
    "module": "kotlinxpath",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fpkywmy4rvbfdh6mqcywu52vpm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-jvm-2.0.jar",
          "url": "kotlinxpath-jvm-2.0.jar",
          "size": 62520,
          "sha512": "ecedc857bc7e5f6ec9f5160309bb460cd43b2fe0d80847fb72fea48f4ca76988b471e09978718d1a34e1889de196b5ad821a7542d39c5110b640d048edd601d0",
          "sha256": "066a3cf25df4bff276b6e8202f47f1532dc579d88d883e816e5978719a70601e",
          "sha1": "2cb3b4dedd78c5f7b97fe80f125491ade104ac90",
          "md5": "bfee7d83d89d98323b2ccf7fb908bfd6"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinxpath-jvm-2.0.jar",
          "url": "kotlinxpath-jvm-2.0.jar",
          "size": 62520,
          "sha512": "ecedc857bc7e5f6ec9f5160309bb460cd43b2fe0d80847fb72fea48f4ca76988b471e09978718d1a34e1889de196b5ad821a7542d39c5110b640d048edd601d0",
          "sha256": "066a3cf25df4bff276b6e8202f47f1532dc579d88d883e816e5978719a70601e",
          "sha1": "2cb3b4dedd78c5f7b97fe80f125491ade104ac90",
          "md5": "bfee7d83d89d98323b2ccf7fb908bfd6"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinxpath-metadata/2.0/kotlinxpath-metadata-2.0.module",
        "group": "io.github.detachhead",
        "module": "kotlinxpath-metadata",
        "version": "2.0"
      }
    }
  ]
}
