{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-M2"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-1.0.7-SNAPSHOT.jar",
          "size": 4492,
          "sha512": "77d6ae69890ebfc891ba05acd364b352767e145dbe2c7b92e0b0cbfbaca996057f94cc7ae6b557c046946585eb5a876a0d87770d1c86aba832bc0c08a63334f6",
          "sha256": "ebdf0718ba746e69a3d29c15151f2b62ee17b1b9757e2c0fa009735da38ef76a",
          "sha1": "c17d3834443fe0d88b004cd41f91e487933426a2",
          "md5": "7fdfeeb4626c8536f6d1d751962ff6d3"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7-SNAPSHOT/url-builder-js-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7-SNAPSHOT/url-builder-js-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7-SNAPSHOT/url-builder-jvm-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7-SNAPSHOT/url-builder-jvm-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7-SNAPSHOT"
      }
    }
  ]
}
