{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.detachhead",
    "module": "url-builder",
    "version": "1.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vqkwyk7omraz3l5apegrx3holu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "url-builder-metadata-1.0.7-SNAPSHOT.jar",
          "url": "url-builder-1.0.7-SNAPSHOT.jar",
          "size": 4494,
          "sha512": "c2e457d9f1c76380a08d969a7d6406df0cd994aefc09cefb812eef68da706d9db92f86d9fb6d916ad40d73780e6d33c94881ac96f1486614160466e76da1e66b",
          "sha256": "1dece6edd38b61fbd34919a158eb15ea6e285841b9bb2e0218ddb55a405b9eca",
          "sha1": "581de095df6f6814610091f912e7e115ba964a58",
          "md5": "c7936008ff37f814fe40e02a2a20eb93"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7-SNAPSHOT/url-builder-js-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../url-builder-js/1.0.7-SNAPSHOT/url-builder-js-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-js",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7-SNAPSHOT/url-builder-jvm-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../url-builder-jvm/1.0.7-SNAPSHOT/url-builder-jvm-1.0.7-SNAPSHOT.module",
        "group": "io.github.detachhead",
        "module": "url-builder-jvm",
        "version": "1.0.7-SNAPSHOT"
      }
    }
  ]
}
